# Исследование потребительской лояльности телекоммуникационной компании

Заказчик этого исследования — большая телекоммуникационная компания, которая оказывает услуги на территории всего СНГ. Перед компанией стоит задача определить текущий уровень потребительской лояльности, или NPS (от англ. Net Promoter Score), среди клиентов из России.

In [3]:
#импортируем библиоотеки
import pandas as pd
from sqlalchemy import create_engine

#путь к файлу
try:
    path_to_db = 'D:/Yandex_practicum/Telecom/telecomm_csi.db'
except:
    path_to_db = '/datasets/telecomm_csi.db'

engine = create_engine(f'sqlite:///{path_to_db}', echo = False)

#формируем SQL-запрос
query = """
SELECT u.user_id, 
    u.lt_day, 
    (CASE 
        WHEN u.lt_day>366 THEN 'старый'
        ELSE 'новый'
    END) AS is_new,
    u.age, 
    (CASE
        WHEN gender_segment = 0 THEN 'мужчина'
        WHEN gender_segment = 1 THEN 'женщина'
        END) AS gender_segment,
    u.os_name, 
    u.cpe_type_name,
    l.country,
    l.city,
    SUBSTR(a.title, 4) AS age_segment,
    SUBSTR(ts.title, 4) AS traffic_segment,
    SUBSTR(ls.title,4) AS lifetime_segment,
    u.nps_score,
    (CASE 
        WHEN nps_score >= 9  THEN 'сторонники' 
        WHEN nps_score <= 6 THEN 'критики' 
        ELSE 'нейтралы' 
        END) AS nps_group
    
    
FROM user AS u 
LEFT JOIN location AS l ON u.location_id=l.location_id
LEFT JOIN age_segment AS a ON u.age_gr_id=a.age_gr_id
LEFT JOIN traffic_segment AS ts ON u.tr_gr_id=ts.tr_gr_id
LEFT JOIN lifetime_segment AS ls ON u.lt_gr_id=ls.lt_gr_id
"""

telecom = pd.read_sql(query, engine)
telecom

,user_id,lt_day,is_new,age,gender_segment,os_name,cpe_type_name,country,city,age_segment,traffic_segment,lifetime_segment,nps_score,nps_group
0,A001A2,2320,старый,45.0,женщина,ANDROID,SMARTPHONE,Россия,Уфа,45-54,1-5,36+,10,сторонники
1,A001WF,2344,старый,53.0,мужчина,ANDROID,SMARTPHONE,Россия,Киров,45-54,1-5,36+,10,сторонники
2,A003Q7,467,старый,57.0,мужчина,ANDROID,SMARTPHONE,Россия,Москва,55-64,20-25,13-24,10,сторонники
3,A004TB,4190,старый,44.0,женщина,IOS,SMARTPHONE,Россия,РостовнаДону,35-44,0.1-1,36+,10,сторонники
4,A004XT,1163,старый,24.0,мужчина,ANDROID,SMARTPHONE,Россия,Рязань,16-24,5-10,36+,10,сторонники
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502488,ZZZKLD,1249,старый,54.0,женщина,ANDROID,SMARTPHONE,Россия,Москва,45-54,1-5,36+,5,критики
502489,ZZZLWY,129,новый,31.0,мужчина,ANDROID,SMARTPHONE,Россия,Москва,25-34,1-5,4-6,8,нейтралы
502490,ZZZQ5F,522,старый,36.0,мужчина,ANDROID,SMARTPHONE,Россия,Сургут,35-44,25-30,13-24,10,сторонники
502491,ZZZQ8E,2936,старый,37.0,женщина,ANDROID,SMARTPHONE,Россия,УланУдэ,35-44,65-70,36+,9,сторонники
502492,ZZZYH0,2471,старый,37.0,мужчина,IOS,SMARTPHONE,Россия,Самара,35-44,10-15,36+,2,критики

# сохраняем файл
telecom.to_csv('C:/Users/user/Downloads/telecom.csv')
telecom.to_csv('D:/Yandex_practicum/Datasets/telecom.csv')

Дашборд
https://public.tableau.com/views/Telecomloyalty/Dashboard1?:language=en-US&publish=yes&:display_count=n&:origin=viz_share_link

Презентация
https://disk.yandex.ru/i/lVFu7vqvjOEi-w